/* ============================================================
   PROJECT DATA — edit this file to update project content.
   ============================================================ */

const PROJECTS = [
  {
    slug:     'clothing-brand',
    index:    '01',
    category: 'Fashion',
    title:    'My Clothing Brand',
    subtitle: 'Personal Apparel Venture',
    year:     '2024–25',
    context:  'Personal Project',
    description: [
      'A self-initiated fashion label built from the ground up — from initial concept and brand identity through to garment design, production, and marketing. The brand merges contemporary streetwear sensibilities with elevated, considered design, targeting a young fashion-forward audience.',
      'The project involved full creative direction across branding, lookbook photography, social media presence, and e-commerce planning. Every touchpoint — from logo to swing tag to product photography — was designed in-house, giving complete control over how the brand communicates at every level.'
    ],
    skills: [
      'Garment Design', 'Brand Identity', 'Creative Direction',
      'Product Development', 'Trend Research', 'Adobe Illustrator',
      'Adobe Photoshop', 'Social Media Marketing', 'Photography'
    ],
    url: 'https://xtcclothing.com/',
    gradient: 'linear-gradient(145deg, #0d0806 0%, #1e120a 40%, #3d2214 100%)',
    imageCount: 95,
    imagePaths: [
      'assets/projects/clothing-brand/XTC SUMMER SHORTS HOODIE T SHIRT JOGGERS-Cover.jpg',
      'assets/projects/clothing-brand/XTC-ZIP-HOODIE-WAR-SS26.png',
      'assets/projects/clothing-brand/XTC-ZIP-HOODIE-WAR-SS26-BACK.png',
      'assets/projects/clothing-brand/XTC-JOGGERS-WAR-SS26.png',
      'assets/projects/clothing-brand/XTC-JOGGERS-WAR-SS26-BACK.png',
      'assets/projects/clothing-brand/girl_in_black_polo_shirt.png',
      'assets/projects/clothing-brand/girl_in_black_polo_shirt_3.png',
      'assets/projects/clothing-brand/girl_in_black_polo_BACK.png',
      'assets/projects/clothing-brand/WHITE_T_FRONT.png',
      'assets/projects/clothing-brand/white_polo_front.png',
      'assets/projects/clothing-brand/white_polo_back.png',
      'assets/projects/clothing-brand/white_tee_back.png',
      'assets/projects/clothing-brand/white_front_2.png',
      'assets/projects/clothing-brand/white_front_3.png',
      'assets/projects/clothing-brand/mens_black_polo_front_2.png',
      'assets/projects/clothing-brand/mens_black_polo_front_4.png',
      'assets/projects/clothing-brand/mens_black_polo_front_5.png',
      'assets/projects/clothing-brand/mens_white_polo_front__Image_Upscaler_Photo_Face.png',
      'assets/projects/clothing-brand/model_black_polo_shirt_Upscaled.png',
      'assets/projects/clothing-brand/black_on_concrete-Photoroom.jpg',
      'assets/projects/clothing-brand/BLACK_GRAPHIC_T.png',
      'assets/projects/clothing-brand/BLACK_GRAPHIC_T_BACK.png',
      'assets/projects/clothing-brand/BLACK-SHORTS-XTC-1080.png',
      'assets/projects/clothing-brand/BLACK-SHORTS-XTC-BACK-1080.png',
      'assets/projects/clothing-brand/ZIP-1080.png',
      'assets/projects/clothing-brand/zip_front.png',
      'assets/projects/clothing-brand/zip_back.png',
      'assets/projects/clothing-brand/cut zip.png',
      'assets/projects/clothing-brand/JOGGERS-1929.png',
      'assets/projects/clothing-brand/joggers_mockup.png',
      'assets/projects/clothing-brand/joggers_front_color.jpeg',
      'assets/projects/clothing-brand/joggers_back_color.jpeg',
      'assets/projects/clothing-brand/joggers_back.jpeg',
      'assets/projects/clothing-brand/back.png',
      'assets/projects/clothing-brand/BACKSKULL.png',
      'assets/projects/clothing-brand/skull_back_graphic.png',
      'assets/projects/clothing-brand/BACK_TECH.jpeg',
      'assets/projects/clothing-brand/BACK_TECH_TEXTURED.jpeg',
      'assets/projects/clothing-brand/FONT_TECH.jpeg',
      'assets/projects/clothing-brand/FONT_TECH_TEXTURED.jpeg',
      'assets/projects/clothing-brand/war_graphic.png',
      'assets/projects/clothing-brand/leather jacket war.png',
      'assets/projects/clothing-brand/CHAOS.png',
      'assets/projects/clothing-brand/DEATH.png',
      'assets/projects/clothing-brand/DROP.png',
      'assets/projects/clothing-brand/DRAWSTRING.png',
      'assets/projects/clothing-brand/LTD-CLEAR.png',
      'assets/projects/clothing-brand/50CAP.png',
      'assets/projects/clothing-brand/JUST BADGE 1920.png',
      'assets/projects/clothing-brand/bone_logo.png',
      'assets/projects/clothing-brand/white_logo.png',
      'assets/projects/clothing-brand/blood_splat.png',
      'assets/projects/clothing-brand/red_10.png',
      'assets/projects/clothing-brand/member.png',
      'assets/projects/clothing-brand/sterling_1080.png',
      'assets/projects/clothing-brand/dead_1920.png',
      'assets/projects/clothing-brand/white_1080.png',
      'assets/projects/clothing-brand/white_1920_logo.png',
      'assets/projects/clothing-brand/1080.png',
      'assets/projects/clothing-brand/1080X1920.png',
      'assets/projects/clothing-brand/COMING SOON 16x9.png',
      'assets/projects/clothing-brand/COMING SOON 1920x1080.png',
      'assets/projects/clothing-brand/plain_banner.png',
      'assets/projects/clothing-brand/concrete_background_insta.png',
      'assets/projects/clothing-brand/Instagram Ad.jpeg',
      'assets/projects/clothing-brand/Untitled-1.png',
      'assets/projects/clothing-brand/Untitled-1_Nero_AI_Image_Upscaler_Photo_Face (1).png',
      'assets/projects/clothing-brand/Untitled_Artwork (61).png',
      'assets/projects/clothing-brand/Untitled_Artwork (76).png',
      'assets/projects/clothing-brand/Untitled_Artwork (79).png',
      'assets/projects/clothing-brand/hf_20260115_225852_efc60dc6-a56e-499d-b66d-d1e1e00db6fc_Nero_AI_Image_Upscaler_Photo_Face.png',
      'assets/projects/clothing-brand/d9ee70c3-3b07-4544-a077-3e24051bbb2b.png',
      'assets/projects/clothing-brand/white_bracelet.png',
      'assets/projects/clothing-brand/white_bracelet_.png',
      'assets/projects/clothing-brand/white_black_bracelet_Nero_AI_Image_Upscaler_Photo_Face.png',
      'assets/projects/clothing-brand/cv_lab_character (2).png',
      'assets/projects/clothing-brand/cv_lab_character (3).png',
      'assets/projects/clothing-brand/cv_lab_character (8).png',
      'assets/projects/clothing-brand/557436558_18065385788346952_7423229752814712261_n..jpg',
      'assets/projects/clothing-brand/557649726_18065385830346952_8999747376200943844_n..jpg',
      'assets/projects/clothing-brand/558376354_18065385797346952_3759812533262391698_n..jpg',
      'assets/projects/clothing-brand/WhatsApp Image 2025-09-19 at 18.32.01_536be41f.jpg',
      'assets/projects/clothing-brand/WhatsApp Image 2025-09-20 at 17.56.20_3a97ce7e.jpg',
      'assets/projects/clothing-brand/WhatsApp Image 2025-09-20 at 17.56.20_43c3a76a.jpg',
      'assets/projects/clothing-brand/WhatsApp Image 2025-09-20 at 17.56.20_8f0d8979.jpg',
      'assets/projects/clothing-brand/WhatsApp Image 2025-09-20 at 17.56.21_7f30efd2.jpg',
      'assets/projects/clothing-brand/WhatsApp Image 2025-09-20 at 17.56.21_ea5b2509.jpg',
      'assets/projects/clothing-brand/WhatsApp Image 2025-09-20 at 17.56.22_b316d3cb.jpg',
      'assets/projects/clothing-brand/WhatsApp Image 2025-09-20 at 17.56.22_bfa973e5.jpg',
      'assets/projects/clothing-brand/WhatsApp Image 2025-09-20 at 18.28.48_5fafed43.jpg',
      'assets/projects/clothing-brand/WhatsApp Image 2025-09-20 at 18.28.48_d4abd437.jpg',
      'assets/projects/clothing-brand/WhatsApp Image 2025-09-20 at 23.29.04_fff02852.jpg',
      'assets/projects/clothing-brand/WhatsApp Image 2025-10-01 at 4.26.55 PM.jpeg',
      'assets/projects/clothing-brand/WhatsApp Image 2026-02-04 at 11.38.29 PM.jpeg',
      'assets/projects/clothing-brand/white al.jpeg'
    ]
  },
  {
    slug:     'named-collective',
    index:    '02',
    category: 'Brand Identity',
    title:    'Named Collective',
    subtitle: 'Brand Strategy & PR Campaign',
    year:     '2024',
    context:  'University — Marketing & PR — 77% First Class',
    description: [
      'A comprehensive brand identity and marketing strategy developed for Named Collective as part of the university Marketing & PR module. The brief required a deep dive into the brand\'s positioning, target consumer, and competitive landscape — culminating in a full campaign proposal.',
      'The project explored digital and physical marketing channels, influencer strategy, and brand communication frameworks. The final submission was awarded a First-Class grade of 77%, recognised for its rigorous research and commercially viable creative direction.'
    ],
    skills: [
      'Brand Strategy', 'Marketing', 'Public Relations',
      'Campaign Planning', 'Consumer Research', 'Copywriting',
      'Adobe InDesign', 'Trend Analysis'
    ],
    gradient: 'linear-gradient(145deg, #060606 0%, #111111 50%, #1c1c1c 100%)',
    imageCount: 73,
    imagePaths: [
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-01.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-02.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-03.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-04.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-05.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-06.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-07.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-08.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-09.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-10.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-11.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-12.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-13.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-14.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-15.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-16.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-17.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-18.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-19.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-20.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-21.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-22.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-23.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-24.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-25.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-26.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-27.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-28.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-29.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-30.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-31.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-32.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-33.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-34.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-35.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-36.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-37.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-38.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-39.png',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-40.png',
      'assets/projects/named-collective/1920X1080.png',
      'assets/projects/named-collective/website_homepage.png',
      'assets/projects/named-collective/competition_post_v2.png',
      'assets/projects/named-collective/competition_post_v3.png',
      'assets/projects/named-collective/competition_post_v4.png',
      'assets/projects/named-collective/competition_post_v5.png',
      'assets/projects/named-collective/Sample_packaging_1.png',
      'assets/projects/named-collective/Mockup_1_Insta_story.png',
      'assets/projects/named-collective/Mockup_1_Insta_story_With_logo.png',
      'assets/projects/named-collective/story_1.png',
      'assets/projects/named-collective/1920.png',
      'assets/projects/named-collective/1920_2.png',
      'assets/projects/named-collective/1.png',
      'assets/projects/named-collective/71a5ea72-1.png',
      'assets/projects/named-collective/ChatGPT Image Nov 4, 2025, 12_22_48 PM.png',
      'assets/projects/named-collective/ChatGPT Image Oct 28, 2025, 02_21_35 PM.png',
      'assets/projects/named-collective/fixed produt.png',
      'assets/projects/named-collective/london.png',
      'assets/projects/named-collective/MUNCkn em eyez.png',
      'assets/projects/named-collective/preferences_logo.webp',
      'assets/projects/named-collective/RFID TAG IMAGE.png',
      'assets/projects/named-collective/transparent_logo (23).png',
      'assets/projects/named-collective/transparent_logo (32).png',
      'assets/projects/named-collective/Underview.png',
      'assets/projects/named-collective/white_white.png',
      'assets/projects/named-collective/WhatsApp Image 2025-09-29 at 1.57.31 PM.jpeg',
      'assets/projects/named-collective/WhatsApp Image 2025-10-28 at 12.33.45 3jpeg.jpeg',
      'assets/projects/named-collective/WhatsApp Image 2025-10-28 at 12.33.45 4.jpeg',
      'assets/projects/named-collective/WhatsApp Image 2025-10-31 at 12.01.34 PM.jpeg',
      'assets/projects/named-collective/WhatsApp Image 2025-11-02 at 12.37.57 CIOMPY.jpeg',
      'assets/projects/named-collective/WhatsApp Image 2025-11-03 at 12.49.03 PM.jpeg',
      'assets/projects/named-collective/WhatsApp Image 2025-11-05 at 2.25.37 AM.jpeg',
      'assets/projects/named-collective/WhatsApp Image 2025-11-06 at 6.01.40 PM.jpeg'
    ]
  },
  {
    slug:     'next-collection',
    index:    '03',
    category: 'Buying & Merchandising',
    title:    'NEXT A/W 25/26 Collection',
    subtitle: 'Fashion Buying & Range Report',
    year:     '2024',
    context:  'University — Buying & Merchandising — 82% First Class (Top Score)',
    description: [
      'An in-depth Autumn/Winter 2025/26 buying report for NEXT, translating trend research into a commercially viable product range. The project involved catwalk analysis, consumer insight, and competitive market research to build a complete buying narrative with specific product, price architecture, and range recommendations.',
      'The report achieved the highest score in the module at 82% and led directly to a formal work experience offer from NEXT\'s buying team — recognition of the commercial rigour and market understanding demonstrated throughout.'
    ],
    skills: [
      'Fashion Buying', 'Range Planning', 'Market Research',
      'Catwalk Analysis', 'Consumer Insight', 'Report Writing',
      'Adobe InDesign', 'Moodboarding'
    ],
    gradient: 'linear-gradient(145deg, #04080f 0%, #091828 40%, #112a45 100%)',
    imageCount: 58,
    imagePaths: [
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-03.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-04.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-05.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-06.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-07.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-08.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-09.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-10.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-11.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-12.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-13.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-14.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-15.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-16.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-17.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-18.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-19.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-20.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-21.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-22.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-23.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-24.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-25.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-26.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-27.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-28.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-29.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-30.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-31.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-32.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-33.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-34.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-35.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-36.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-37.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-39.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-40.png',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-41.png',
      'assets/projects/next-collection/Next Award.png',
      'assets/projects/next-collection/IMG_0600.PNG',
      'assets/projects/next-collection/IMG_0601.PNG',
      'assets/projects/next-collection/IMG_0602.PNG',
      'assets/projects/next-collection/IMG_0603.PNG',
      'assets/projects/next-collection/IMG_0604.PNG',
      'assets/projects/next-collection/IMG_0605.PNG',
      'assets/projects/next-collection/IMG_0606.PNG',
      'assets/projects/next-collection/IMG_0607.PNG',
      'assets/projects/next-collection/IMG_0608.PNG',
      'assets/projects/next-collection/IMG_0609.PNG',
      'assets/projects/next-collection/IMG_0610.PNG',
      'assets/projects/next-collection/IMG_0611.PNG',
      'assets/projects/next-collection/IMG_0612.PNG',
      'assets/projects/next-collection/IMG_0613.PNG',
      'assets/projects/next-collection/IMG_0616.PNG',
      'assets/projects/next-collection/IMG_0617.PNG',
      'assets/projects/next-collection/IMG_0618.PNG',
      'assets/projects/next-collection/Untitled_Artwork (58).png',
      'assets/projects/next-collection/Untitled_Artwork 1 (17).png'
    ]
  },
  {
    slug:     'trimas-internship',
    index:    '04',
    category: 'Marketing',
    title:    'TriMas Internship',
    subtitle: 'Corporate Marketing Experience',
    year:     '2024',
    context:  'Professional — Marketing Internship',
    description: [
      'A hands-on marketing internship with TriMas, gaining real-world experience across brand strategy, campaign execution, and digital marketing. The role involved creating marketing collateral, supporting campaign launches, and contributing to the company\'s wider brand communications.',
      'The internship provided invaluable exposure to corporate marketing workflows, stakeholder management, and the pace of professional creative production — bridging the gap between academic theory and commercial reality.'
    ],
    skills: [
      'Digital Marketing', 'Campaign Management', 'Content Creation',
      'Brand Strategy', 'Adobe Creative Suite', 'Copywriting',
      'Project Management', 'Stakeholder Communication'
    ],
    gradient: 'linear-gradient(145deg, #06060f 0%, #0e0e28 50%, #181840 100%)',
    imageCount: 36,
    imagePaths: [
      'assets/projects/trimas-internship/3group_v2.png',
      'assets/projects/trimas-internship/Mockup 2 1.jpg',
      'assets/projects/trimas-internship/Mockup 4 1.jpg',
      'assets/projects/trimas-internship/Mockup 5 1.jpg',
      'assets/projects/trimas-internship/Mockup 7 1.jpg',
      'assets/projects/trimas-internship/Mockup 10.jpg',
      'assets/projects/trimas-internship/Mockup 11 1.jpg',
      'assets/projects/trimas-internship/Mockup 12 2.jpg',
      'assets/projects/trimas-internship/Mockup 12 2 (1).jpg',
      'assets/projects/trimas-internship/Mockup 13 1.jpg',
      'assets/projects/trimas-internship/Mockup 14 1.jpg',
      'assets/projects/trimas-internship/Mockup 15 1.jpg',
      'assets/projects/trimas-internship/Drinktec_Social_media.png',
      'assets/projects/trimas-internship/Drinktec_Social_media13.png',
      'assets/projects/trimas-internship/Drinktec_Social_media14.png',
      'assets/projects/trimas-internship/Drinktec_Social_media16.png',
      'assets/projects/trimas-internship/beauty bottles.png',
      'assets/projects/trimas-internship/all pull caps in water.png',
      'assets/projects/trimas-internship/flip_caps_in_water.png',
      'assets/projects/trimas-internship/bottle_caps.png',
      'assets/projects/trimas-internship/bottles_with_greenry.png',
      'assets/projects/trimas-internship/bottlers_flowers.png',
      'assets/projects/trimas-internship/beach.png',
      'assets/projects/trimas-internship/drink.png',
      'assets/projects/trimas-internship/Orange_pull.png',
      'assets/projects/trimas-internship/Isqueeze.png',
      'assets/projects/trimas-internship/Sports_Cap_graphic.png',
      'assets/projects/trimas-internship/final layout.png',
      'assets/projects/trimas-internship/finalve.png',
      'assets/projects/trimas-internship/base2.png',
      'assets/projects/trimas-internship/asasas.png',
      'assets/projects/trimas-internship/ChatGPT Image Jul 11, 2025, 02_52_35 PM.png',
      'assets/projects/trimas-internship/f53eca67-ccdb-4b13-8320-6141b2f922bc.png',
      'assets/projects/trimas-internship/Untitled-2.png',
      'assets/projects/trimas-internship/Untitled-6.png',
      'assets/projects/trimas-internship/Untitled-7.png'
    ]
  },
  {
    slug:     'selfridges-project',
    index:    '05',
    category: 'Retail Design',
    title:    'Selfridges Project',
    subtitle: 'Visual Merchandising & Retail Strategy',
    year:     '2024',
    context:  'University — Visual Merchandising — 67% Upper Second Class',
    description: [
      'A visual merchandising concept developed for Selfridges as part of the university Visual Merchandising module. The project explored the intersection of retail design, consumer experience, and brand storytelling within one of the UK\'s most iconic department stores.',
      'The brief required a full concept presentation covering window displays, in-store layouts, and experiential retail strategies — all grounded in Selfridges\' luxury positioning and target consumer profile. The work balanced aesthetic ambition with commercial pragmatism.'
    ],
    skills: [
      'Visual Merchandising', 'Retail Design', 'Space Planning',
      'Consumer Experience', 'Brand Storytelling', 'Concept Development',
      'Adobe InDesign', 'Sketch Rendering'
    ],
    gradient: 'linear-gradient(145deg, #0e0703 0%, #3a1a08 40%, #7a3510 100%)',
    imageCount: 68,
    imagePaths: [
      'assets/projects/selfridges-project/thumbnail_IMG_2787.jpg',
      'assets/projects/selfridges-project/WhatsApp Image 2025-09-22 at 14.47.31_c054d6cf.jpg',
      'assets/projects/selfridges-project/AI_GENERATED_,MOCKUP.jpeg',
      'assets/projects/selfridges-project/WhatsApp Image 2025-05-19 at 3.28.38 PM.jpeg',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-0.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-1.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-2.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-3.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-4.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-5.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-6.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-7.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-8.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-9.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-10.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-11.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-12.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-13.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-14.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-15.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-16.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-17.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-18.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-19.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-20.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-21.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-22.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-23.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-24.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-25.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-26.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-27.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-28.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-29.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-30.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-31.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-32.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-33.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-34.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-35.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-36.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-37.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-38.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-39.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-40.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-41.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-42.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-43.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-44.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-45.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-46.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-47.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-48.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-49.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-50.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-51.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-52.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-53.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-54.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-55.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-56.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-57.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-58.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-59.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-60.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-61.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-62.png',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-63.png'
    ]
  },
  {
    slug:     'cv-lab',
    index:    '06',
    category: 'Digital Product',
    title:    'CV Lab SaaS',
    subtitle: 'UI/UX Design for a CV Building Platform',
    year:     '2025',
    context:  'Personal Project — Product Design',
    description: [
      'End-to-end UI/UX design for CV Lab — a Software-as-a-Service platform that helps users create, optimise, and export professional CVs. The project covered the full design process from user research and wireframing through to high-fidelity prototyping and design system creation.',
      'The platform\'s interface prioritises clarity and ease of use, with a modern, professional aesthetic that gives users confidence in the product they\'re building. A comprehensive component library was built in Figma to ensure consistency across every screen state and interaction.'
    ],
    skills: [
      'UI Design', 'UX Research', 'Figma', 'Prototyping',
      'Design Systems', 'User Flows', 'Wireframing',
      'Component Design', 'Accessibility'
    ],
    gradient: 'linear-gradient(145deg, #02050c 0%, #060f1e 50%, #0a1830 100%)',
    imageCount: 15,
    imagePaths: [
      'assets/projects/cv-lab/cv banner.png',
      'assets/projects/cv-lab/BACKGROUND.png',
      'assets/projects/cv-lab/check_your_cv.png',
      'assets/projects/cv-lab/cv_analysis.png',
      'assets/projects/cv-lab/make_cv_with_ai.png',
      'assets/projects/cv-lab/cv_lab_intro_slide_1.png',
      'assets/projects/cv-lab/cv_lab_intro_slide_2.png',
      'assets/projects/cv-lab/cv_lab_intro_slide_3.png',
      'assets/projects/cv-lab/logo.png',
      'assets/projects/cv-lab/post1.png',
      'assets/projects/cv-lab/photo_2025-10-26_21-10-37.jpg',
      'assets/projects/cv-lab/Screenshot 2026-02-12 152701.png',
      'assets/projects/cv-lab/Screenshot 2026-02-12 152733.png',
      'assets/projects/cv-lab/Screenshot 2026-02-12 152759.png',
      'assets/projects/cv-lab/Screenshot 2026-02-12 152820.png'
    ]
  },
  {
    slug:     'graphic-design',
    index:    '07',
    category: 'Graphic Design',
    title:    'Graphic Design Showcase',
    subtitle: 'Selected Works Across Multiple Briefs',
    year:     '2023–25',
    context:  'Various — Personal & University Projects',
    description: [
      'A curated selection of graphic design work spanning personal projects, university briefs, and commercial experiments. The showcase demonstrates versatility across visual identities, editorial layouts, digital graphics, and illustration.',
      'Each piece represents a distinct design challenge — from minimal typographic compositions to bold, colour-driven brand materials — united by a consistent commitment to craft and visual impact. The body of work reflects an evolving design sensibility shaped by fashion, culture, and digital media.'
    ],
    skills: [
      'Graphic Design', 'Typography', 'Brand Identity',
      'Editorial Design', 'Adobe Illustrator', 'Adobe Photoshop',
      'Adobe InDesign', 'Digital Illustration', 'Layout Design'
    ],
    gradient: 'linear-gradient(135deg, #0a0316 0%, #1a0840 30%, #4a0f90 60%, #8f0028 100%)',
    imageCount: 0,
    imagePaths: []
  },
  {
    slug:     'trend-forecasting',
    index:    '08',
    category: 'Trend Forecasting',
    title:    'Trend Forecasting',
    subtitle: 'Culture, Cycles & Consumer Behaviour',
    year:     '2024',
    context:  'University — Trend Forecasting Module',
    description: [
      'A university module dedicated to understanding how fashion trend cycles originate, develop, and eventually filter down through the market. The project required deep cultural research — analysing how music, art, street culture, social movements, and emerging subcultures influence what people wear and how those signals translate into mainstream commercial fashion.',
      'The work explored the full lifecycle of a trend: from the early adopters and cultural moments that spark it, through the tipping points where it enters the fashion consciousness, to the point of mass adoption and eventual saturation. Understanding this cycle is central to making informed decisions in buying, design, and brand strategy.',
      'The module developed strong skills in cultural analysis, trend reporting, and the ability to read emerging signals before they reach the mainstream — skills that directly informed the NEXT A/W 25/26 Collection buying report produced in the same year.'
    ],
    skills: [
      'Trend Forecasting', 'Cultural Analysis', 'Consumer Research',
      'Trend Reporting', 'Moodboarding', 'Adobe InDesign',
      'Market Research', 'Fashion Theory'
    ],
    gradient: 'linear-gradient(145deg, #080c10 0%, #101c2a 35%, #0e2840 60%, #1a3a1a 100%)',
    imageCount: 37,
    imagePaths: [
      'assets/projects/trend-forecasting/Trend Forcasting-01.png',
      'assets/projects/trend-forecasting/Trend Forcasting-02.png',
      'assets/projects/trend-forecasting/Trend Forcasting-03.png',
      'assets/projects/trend-forecasting/Trend Forcasting-04.png',
      'assets/projects/trend-forecasting/Trend Forcasting-05.png',
      'assets/projects/trend-forecasting/Trend Forcasting-06.png',
      'assets/projects/trend-forecasting/Trend Forcasting-07.png',
      'assets/projects/trend-forecasting/Trend Forcasting-08.png',
      'assets/projects/trend-forecasting/Trend Forcasting-09.png',
      'assets/projects/trend-forecasting/Trend Forcasting-10.png',
      'assets/projects/trend-forecasting/Trend Forcasting-11.png',
      'assets/projects/trend-forecasting/Trend Forcasting-12.png',
      'assets/projects/trend-forecasting/Trend Forcasting-13.png',
      'assets/projects/trend-forecasting/Trend Forcasting-14.png',
      'assets/projects/trend-forecasting/Trend Forcasting-15.png',
      'assets/projects/trend-forecasting/Trend Forcasting-16.png',
      'assets/projects/trend-forecasting/Trend Forcasting-17.png',
      'assets/projects/trend-forecasting/Trend Forcasting-18.png',
      'assets/projects/trend-forecasting/Trend Forcasting-19.png',
      'assets/projects/trend-forecasting/Trend Forcasting-20.png',
      'assets/projects/trend-forecasting/Trend Forcasting-21.png',
      'assets/projects/trend-forecasting/Trend Forcasting-22.png',
      'assets/projects/trend-forecasting/Trend Forcasting-23.png',
      'assets/projects/trend-forecasting/Trend Forcasting-24.png',
      'assets/projects/trend-forecasting/Trend Forcasting-25.png',
      'assets/projects/trend-forecasting/Trend Forcasting-26.png',
      'assets/projects/trend-forecasting/Trend Forcasting-27.png',
      'assets/projects/trend-forecasting/Trend Forcasting-28.png',
      'assets/projects/trend-forecasting/Trend Forcasting-29.png',
      'assets/projects/trend-forecasting/Trend Forcasting-30.png',
      'assets/projects/trend-forecasting/Trend Zeitgeist Pack with Garement-1.png',
      'assets/projects/trend-forecasting/Trend Zeitgeist Pack with Garement-2.png',
      'assets/projects/trend-forecasting/Trend Zeitgeist Pack with Garement-3.png',
      'assets/projects/trend-forecasting/Trend Zeitgeist Pack with Garement-4.png',
      'assets/projects/trend-forecasting/Trend Zeitgeist Pack with Garement-5.png',
      'assets/projects/trend-forecasting/Trend Zeitgeist Pack with Garement-6.png',
      'assets/projects/trend-forecasting/Trend Zeitgeist Pack with Garement-7.png'
    ]
  },
  {
    slug:     'slimmer-app',
    index:    '09',
    category: 'App Design',
    title:    'Slimmer App',
    subtitle: 'AI-Powered Women\'s Fitness',
    year:     '2025',
    context:  'Personal Project — UI/UX & Product Design',
    description: [
      'Slimmer is a women\'s fitness app designed around the idea that no two bodies are the same. Using AI-powered facial scanning, the app analyses the user\'s face to identify their personal focus areas and generates a tailored workout plan targeting those specific zones — removing the guesswork from fitness and making personalised training accessible to everyone.',
      'The nutrition side of the app uses food photo recognition to automatically log meals. Users simply take a photo of what they\'re eating and the AI identifies the food, estimates portion size, and logs the calories and macros instantly. Water intake tracking is built in alongside, giving users a complete picture of their daily health without manual data entry.',
      'The product was designed with a clean, premium aesthetic aimed at women who want results without complexity. Every interaction — from the onboarding facial scan to the daily dashboard — was designed to feel intuitive, motivating, and visually considered.'
    ],
    skills: [
      'UI/UX Design', 'Mobile App Design', 'Figma',
      'Prototyping', 'User Research', 'AI Integration',
      'Product Design', 'Visual Design', 'Branding'
    ],
    gradient: 'linear-gradient(145deg, #0f0018 0%, #240030 35%, #3d0050 60%, #5a0060 80%, #2a0030 100%)',
    imageCount: 61,
    imagePaths: [
      'assets/projects/slimmer-app/photo_2026-04-16_22-19-47.jpg',
      'assets/projects/slimmer-app/launch screen.png',
      'assets/projects/slimmer-app/Get Started.png',
      'assets/projects/slimmer-app/greeting page.png',
      'assets/projects/slimmer-app/enter name.png',
      'assets/projects/slimmer-app/enter age.png',
      'assets/projects/slimmer-app/enter height.png',
      'assets/projects/slimmer-app/Whats your weight.png',
      'assets/projects/slimmer-app/how would you describe your face & body.png',
      'assets/projects/slimmer-app/what do you want to work on.png',
      'assets/projects/slimmer-app/what are your weight related goals.png',
      'assets/projects/slimmer-app/How Much time do you have today.png',
      'assets/projects/slimmer-app/when did you last feel happy.png',
      'assets/projects/slimmer-app/what do you want to acheive.png',
      'assets/projects/slimmer-app/building plan.png',
      'assets/projects/slimmer-app/results page.png',
      'assets/projects/slimmer-app/home page.jpg',
      'assets/projects/slimmer-app/calorie tracker screen.png',
      'assets/projects/slimmer-app/paywall 1.png',
      'assets/projects/slimmer-app/Testimonails sceen.png',
      'assets/projects/slimmer-app/Notifcations.png',
      'assets/projects/slimmer-app/camera permissions.png',
      'assets/projects/slimmer-app/privacy screen.png',
      'assets/projects/slimmer-app/SLIMMER_APP_LOGO.png',
      'assets/projects/slimmer-app/backup.png',
      'assets/projects/slimmer-app/CALORIES-A.png',
      'assets/projects/slimmer-app/CALORIES-B.png',
      'assets/projects/slimmer-app/PERSONALIZED-A.png',
      'assets/projects/slimmer-app/PERSONALIZED-B.png',
      'assets/projects/slimmer-app/SMARTINSIGHT-A.png',
      'assets/projects/slimmer-app/SMARTINSIGHT-B.png',
      'assets/projects/slimmer-app/21days.png',
      'assets/projects/slimmer-app/slide_2.png',
      'assets/projects/slimmer-app/slide_3.png',
      'assets/projects/slimmer-app/slimmer_add1.png',
      'assets/projects/slimmer-app/menopause_ad.png',
      'assets/projects/slimmer-app/lymphatic.png',
      'assets/projects/slimmer-app/look younger.jpg',
      'assets/projects/slimmer-app/Acheive your Dream Body.png',
      'assets/projects/slimmer-app/are you ready for change.png',
      'assets/projects/slimmer-app/by taking action today.png',
      'assets/projects/slimmer-app/Did you know.png',
      'assets/projects/slimmer-app/Harvard quote.png',
      'assets/projects/slimmer-app/in just 2 weeks#.png',
      'assets/projects/slimmer-app/the face & body you miss.png',
      'assets/projects/slimmer-app/what you could start to see.png',
      'assets/projects/slimmer-app/your all set.png',
      'assets/projects/slimmer-app/1.png',
      'assets/projects/slimmer-app/2.png',
      'assets/projects/slimmer-app/3.png',
      'assets/projects/slimmer-app/4.png',
      'assets/projects/slimmer-app/5.png',
      'assets/projects/slimmer-app/6.png',
      'assets/projects/slimmer-app/7.png',
      'assets/projects/slimmer-app/8.png',
      'assets/projects/slimmer-app/9.png',
      'assets/projects/slimmer-app/10.png',
      'assets/projects/slimmer-app/11.png',
      'assets/projects/slimmer-app/12.png',
      'assets/projects/slimmer-app/13.png'
    ]
  },
  {
    slug:     'make-progress',
    index:    '10',
    category: 'Brand Identity',
    title:    'Make Progress',
    subtitle: 'Event Branding & Paid Social',
    year:     '2023',
    context:  'Freelance — Brand Identity & Meta Advertising',
    description: [
      'Make Progress was a community event held in Birmingham city centre, bringing together local businesses from across the learning, skills, sport, and community sectors under one roof and presenting them directly to the public. The concept was simple: give people in the city access to opportunities they might not have otherwise discovered — all in one place.',
      'My role was to create the brand identity from scratch and run Meta advertising campaigns targeting local businesses, encouraging them to purchase a stall plot at the event. This meant building a visual language that communicated energy, inclusivity, and opportunity, while the ad campaigns needed to convert business owners who had never heard of the event.',
      'Looking back, this was one of my earliest professional design projects and a formative experience — both in client communication and in understanding how brand and marketing work together. The work taught me a great deal about the commercial realities of design. With the skills I have now, I would approach the visual identity very differently, but the experience of running live paid campaigns, managing creative assets, and delivering to a real brief was invaluable at that stage of my career.'
    ],
    skills: [
      'Brand Identity', 'Logo Design', 'Meta Ads',
      'Paid Social', 'Copywriting', 'Adobe Illustrator',
      'Adobe Photoshop', 'Event Design', 'Marketing Strategy'
    ],
    gradient: 'linear-gradient(145deg, #0a0e06 0%, #141e08 35%, #1e300a 60%, #2a420e 100%)',
    imageCount: 0,
    imagePaths: []
  }
];
