/* ============================================================
   PROJECT DATA,edit this file to update project content.
   ============================================================ */

const PROJECTS = [
  {
    slug:     'clothing-brand',
    index:    '01',
    category: 'Fashion',
    title:    'My Clothing Brand',
    subtitle: 'Personal Apparel Venture',
    year:     '2024–25',
    context:  'Personal Project',
    description: [
      'A clothing brand I built from scratch. Started with the concept and brand identity, then moved into actual garment design, production and marketing. The aim was something that sits between real streetwear and something a bit more considered and elevated.',
      'I handled full creative direction across branding, photography, social media and e-commerce planning. Every touchpoint from the logo to the swing tag was done in-house, which meant complete control over how the brand came across.'
    ],
    skills: [
      'Garment Design', 'Brand Identity', 'Creative Direction',
      'Product Development', 'Trend Research', 'Adobe Illustrator',
      'Adobe Photoshop', 'Social Media Marketing', 'Photography'
    ],
    url: 'https://xtcclothing.com/',
    gradient: 'linear-gradient(145deg, #0d0806 0%, #1e120a 40%, #3d2214 100%)',
    imageCount: 95,
    imagePaths: [
      'assets/projects/clothing-brand/XTC SUMMER SHORTS HOODIE T SHIRT JOGGERS-Cover.webp',
      'assets/projects/clothing-brand/XTC-ZIP-HOODIE-WAR-SS26.webp',
      'assets/projects/clothing-brand/XTC-ZIP-HOODIE-WAR-SS26-BACK.webp',
      'assets/projects/clothing-brand/XTC-JOGGERS-WAR-SS26.webp',
      'assets/projects/clothing-brand/XTC-JOGGERS-WAR-SS26-BACK.webp',
      'assets/projects/clothing-brand/girl_in_black_polo_shirt.webp',
      'assets/projects/clothing-brand/girl_in_black_polo_shirt_3.webp',
      'assets/projects/clothing-brand/girl_in_black_polo_BACK.webp',
      'assets/projects/clothing-brand/WHITE_T_FRONT.webp',
      'assets/projects/clothing-brand/white_polo_front.webp',
      'assets/projects/clothing-brand/white_polo_back.webp',
      'assets/projects/clothing-brand/white_tee_back.webp',
      'assets/projects/clothing-brand/white_front_2.webp',
      'assets/projects/clothing-brand/white_front_3.webp',
      'assets/projects/clothing-brand/mens_black_polo_front_2.webp',
      'assets/projects/clothing-brand/mens_black_polo_front_4.webp',
      'assets/projects/clothing-brand/mens_black_polo_front_5.webp',
      'assets/projects/clothing-brand/mens_white_polo_front__Image_Upscaler_Photo_Face.webp',
      'assets/projects/clothing-brand/model_black_polo_shirt_Upscaled.webp',
      'assets/projects/clothing-brand/black_on_concrete-Photoroom.webp',
      'assets/projects/clothing-brand/BLACK_GRAPHIC_T.webp',
      'assets/projects/clothing-brand/BLACK_GRAPHIC_T_BACK.webp',
      'assets/projects/clothing-brand/BLACK-SHORTS-XTC-1080.webp',
      'assets/projects/clothing-brand/BLACK-SHORTS-XTC-BACK-1080.webp',
      'assets/projects/clothing-brand/ZIP-1080.webp',
      'assets/projects/clothing-brand/zip_front.webp',
      'assets/projects/clothing-brand/zip_back.webp',
      'assets/projects/clothing-brand/cut zip.webp',
      'assets/projects/clothing-brand/JOGGERS-1929.webp',
      'assets/projects/clothing-brand/joggers_mockup.webp',
      'assets/projects/clothing-brand/joggers_front_color.webp',
      'assets/projects/clothing-brand/joggers_back_color.webp',
      'assets/projects/clothing-brand/joggers_back.webp',
      'assets/projects/clothing-brand/back.webp',
      'assets/projects/clothing-brand/BACKSKULL.webp',
      'assets/projects/clothing-brand/skull_back_graphic.webp',
      'assets/projects/clothing-brand/BACK_TECH.webp',
      'assets/projects/clothing-brand/BACK_TECH_TEXTURED.webp',
      'assets/projects/clothing-brand/FONT_TECH.webp',
      'assets/projects/clothing-brand/FONT_TECH_TEXTURED.webp',
      'assets/projects/clothing-brand/war_graphic.webp',
      'assets/projects/clothing-brand/leather jacket war.webp',
      'assets/projects/clothing-brand/CHAOS.webp',
      'assets/projects/clothing-brand/DEATH.webp',
      'assets/projects/clothing-brand/DROP.webp',
      'assets/projects/clothing-brand/DRAWSTRING.webp',
      'assets/projects/clothing-brand/LTD-CLEAR.webp',
      'assets/projects/clothing-brand/50CAP.webp',
      'assets/projects/clothing-brand/JUST BADGE 1920.webp',
      'assets/projects/clothing-brand/bone_logo.webp',
      'assets/projects/clothing-brand/white_logo.webp',
      'assets/projects/clothing-brand/blood_splat.webp',
      'assets/projects/clothing-brand/red_10.webp',
      'assets/projects/clothing-brand/member.webp',
      'assets/projects/clothing-brand/sterling_1080.webp',
      'assets/projects/clothing-brand/dead_1920.webp',
      'assets/projects/clothing-brand/white_1080.webp',
      'assets/projects/clothing-brand/white_1920_logo.webp',
      'assets/projects/clothing-brand/1080.webp',
      'assets/projects/clothing-brand/1080X1920.webp',
      'assets/projects/clothing-brand/COMING SOON 16x9.webp',
      'assets/projects/clothing-brand/COMING SOON 1920x1080.webp',
      'assets/projects/clothing-brand/plain_banner.webp',
      'assets/projects/clothing-brand/concrete_background_insta.webp',
      'assets/projects/clothing-brand/Instagram Ad.webp',
      'assets/projects/clothing-brand/Untitled-1.webp',
      'assets/projects/clothing-brand/Untitled-1_Nero_AI_Image_Upscaler_Photo_Face (1).webp',
      'assets/projects/clothing-brand/Untitled_Artwork (61).webp',
      'assets/projects/clothing-brand/Untitled_Artwork (76).webp',
      'assets/projects/clothing-brand/Untitled_Artwork (79).webp',
      'assets/projects/clothing-brand/hf_20260115_225852_efc60dc6-a56e-499d-b66d-d1e1e00db6fc_Nero_AI_Image_Upscaler_Photo_Face.webp',
      'assets/projects/clothing-brand/d9ee70c3-3b07-4544-a077-3e24051bbb2b.webp',
      'assets/projects/clothing-brand/white_bracelet.webp',
      'assets/projects/clothing-brand/white_bracelet_.webp',
      'assets/projects/clothing-brand/white_black_bracelet_Nero_AI_Image_Upscaler_Photo_Face.webp',
      'assets/projects/clothing-brand/cv_lab_character (2).webp',
      'assets/projects/clothing-brand/cv_lab_character (3).webp',
      'assets/projects/clothing-brand/cv_lab_character (8).webp',
      'assets/projects/clothing-brand/557436558_18065385788346952_7423229752814712261_n..webp',
      'assets/projects/clothing-brand/557649726_18065385830346952_8999747376200943844_n..webp',
      'assets/projects/clothing-brand/558376354_18065385797346952_3759812533262391698_n..webp',
      'assets/projects/clothing-brand/WhatsApp Image 2025-09-19 at 18.32.01_536be41f.webp',
      'assets/projects/clothing-brand/WhatsApp Image 2025-09-20 at 17.56.20_3a97ce7e.webp',
      'assets/projects/clothing-brand/WhatsApp Image 2025-09-20 at 17.56.20_43c3a76a.webp',
      'assets/projects/clothing-brand/WhatsApp Image 2025-09-20 at 17.56.20_8f0d8979.webp',
      'assets/projects/clothing-brand/WhatsApp Image 2025-09-20 at 17.56.21_7f30efd2.webp',
      'assets/projects/clothing-brand/WhatsApp Image 2025-09-20 at 17.56.21_ea5b2509.webp',
      'assets/projects/clothing-brand/WhatsApp Image 2025-09-20 at 17.56.22_b316d3cb.webp',
      'assets/projects/clothing-brand/WhatsApp Image 2025-09-20 at 17.56.22_bfa973e5.webp',
      'assets/projects/clothing-brand/WhatsApp Image 2025-09-20 at 18.28.48_5fafed43.webp',
      'assets/projects/clothing-brand/WhatsApp Image 2025-09-20 at 18.28.48_d4abd437.webp',
      'assets/projects/clothing-brand/WhatsApp Image 2025-09-20 at 23.29.04_fff02852.webp',
      'assets/projects/clothing-brand/WhatsApp Image 2025-10-01 at 4.26.55 PM.webp',
      'assets/projects/clothing-brand/WhatsApp Image 2026-02-04 at 11.38.29 PM.webp',
      'assets/projects/clothing-brand/white al.webp'
    ]
  },
  {
    slug:     'named-collective',
    index:    '02',
    category: 'Brand Identity',
    title:    'Named Collective',
    subtitle: 'Brand Strategy & PR Campaign',
    year:     '2024',
    context:  'University,Marketing & PR,77% First Class',
    description: [
      'A full brand identity and marketing strategy for Named Collective, done as part of my university Marketing and PR module. The brief needed proper research into their positioning, their consumer and where they sat against competitors, all pulled together into a campaign proposal.',
      'I looked into digital and physical marketing channels, influencer strategy and how the brand communicates. Got 77% and a First Class on the final submission, which I was well happy with.'
    ],
    skills: [
      'Brand Strategy', 'Marketing', 'Public Relations',
      'Campaign Planning', 'Consumer Research', 'Copywriting',
      'Adobe InDesign', 'Trend Analysis'
    ],
    gradient: 'linear-gradient(145deg, #060606 0%, #111111 50%, #1c1c1c 100%)',
    imageCount: 73,
    imagePaths: [
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-01.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-02.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-03.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-04.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-05.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-06.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-07.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-08.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-09.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-10.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-11.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-12.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-13.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-14.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-15.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-16.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-17.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-18.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-19.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-20.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-21.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-22.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-23.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-24.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-25.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-26.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-27.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-28.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-29.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-30.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-31.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-32.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-33.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-34.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-35.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-36.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-37.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-38.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-39.webp',
      'assets/projects/named-collective/Campaign - Joseph Byrne - Named Collective-40.webp',
      'assets/projects/named-collective/1920X1080.webp',
      'assets/projects/named-collective/website_homepage.webp',
      'assets/projects/named-collective/competition_post_v2.webp',
      'assets/projects/named-collective/competition_post_v3.webp',
      'assets/projects/named-collective/competition_post_v4.webp',
      'assets/projects/named-collective/competition_post_v5.webp',
      'assets/projects/named-collective/Sample_packaging_1.webp',
      'assets/projects/named-collective/Mockup_1_Insta_story.webp',
      'assets/projects/named-collective/Mockup_1_Insta_story_With_logo.webp',
      'assets/projects/named-collective/story_1.webp',
      'assets/projects/named-collective/1920.webp',
      'assets/projects/named-collective/1920_2.webp',
      'assets/projects/named-collective/1.webp',
      'assets/projects/named-collective/71a5ea72-1.webp',
      'assets/projects/named-collective/ChatGPT Image Nov 4, 2025, 12_22_48 PM.webp',
      'assets/projects/named-collective/ChatGPT Image Oct 28, 2025, 02_21_35 PM.webp',
      'assets/projects/named-collective/fixed produt.webp',
      'assets/projects/named-collective/london.webp',
      'assets/projects/named-collective/MUNCkn em eyez.webp',
      'assets/projects/named-collective/preferences_logo.webp',
      'assets/projects/named-collective/RFID TAG IMAGE.webp',
      'assets/projects/named-collective/transparent_logo (23).webp',
      'assets/projects/named-collective/transparent_logo (32).webp',
      'assets/projects/named-collective/Underview.webp',
      'assets/projects/named-collective/white_white.webp',
      'assets/projects/named-collective/WhatsApp Image 2025-09-29 at 1.57.31 PM.webp',
      'assets/projects/named-collective/WhatsApp Image 2025-10-28 at 12.33.45 3jpeg.webp',
      'assets/projects/named-collective/WhatsApp Image 2025-10-28 at 12.33.45 4.webp',
      'assets/projects/named-collective/WhatsApp Image 2025-10-31 at 12.01.34 PM.webp',
      'assets/projects/named-collective/WhatsApp Image 2025-11-02 at 12.37.57 CIOMPY.webp',
      'assets/projects/named-collective/WhatsApp Image 2025-11-03 at 12.49.03 PM.webp',
      'assets/projects/named-collective/WhatsApp Image 2025-11-05 at 2.25.37 AM.webp',
      'assets/projects/named-collective/WhatsApp Image 2025-11-06 at 6.01.40 PM.webp'
    ]
  },
  {
    slug:     'next-collection',
    index:    '03',
    category: 'Buying & Merchandising',
    title:    'NEXT A/W 25/26 Collection',
    subtitle: 'Fashion Buying & Range Report',
    year:     '2024',
    context:  'University,Buying & Merchandising,82% First Class (Top Score)',
    description: [
      'A detailed A/W 25/26 buying report for NEXT. I took trend research and turned it into an actual product range, covering catwalk analysis, consumer insight, competitive research and proper range recommendations with pricing.',
      'Got 82%, the top score in the module. NEXT\'s buying team liked it enough to send through a formal work experience offer, which was a proper result.'
    ],
    skills: [
      'Fashion Buying', 'Range Planning', 'Market Research',
      'Catwalk Analysis', 'Consumer Insight', 'Report Writing',
      'Adobe InDesign', 'Moodboarding'
    ],
    gradient: 'linear-gradient(145deg, #04080f 0%, #091828 40%, #112a45 100%)',
    imageCount: 58,
    imagePaths: [
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-03.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-04.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-05.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-06.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-07.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-08.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-09.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-10.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-11.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-12.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-13.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-14.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-15.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-16.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-17.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-18.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-19.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-20.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-21.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-22.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-23.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-24.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-25.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-26.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-27.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-28.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-29.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-30.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-31.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-32.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-33.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-34.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-35.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-36.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-37.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-39.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-40.webp',
      'assets/projects/next-collection/Range Book For Next (Buying & Merchandising)-41.webp',
      'assets/projects/next-collection/Next Award.webp',
      'assets/projects/next-collection/IMG_0600.webp',
      'assets/projects/next-collection/IMG_0601.webp',
      'assets/projects/next-collection/IMG_0602.webp',
      'assets/projects/next-collection/IMG_0603.webp',
      'assets/projects/next-collection/IMG_0604.webp',
      'assets/projects/next-collection/IMG_0605.webp',
      'assets/projects/next-collection/IMG_0606.webp',
      'assets/projects/next-collection/IMG_0607.webp',
      'assets/projects/next-collection/IMG_0608.webp',
      'assets/projects/next-collection/IMG_0609.webp',
      'assets/projects/next-collection/IMG_0610.webp',
      'assets/projects/next-collection/IMG_0611.webp',
      'assets/projects/next-collection/IMG_0612.webp',
      'assets/projects/next-collection/IMG_0613.webp',
      'assets/projects/next-collection/IMG_0616.webp',
      'assets/projects/next-collection/IMG_0617.webp',
      'assets/projects/next-collection/IMG_0618.webp',
      'assets/projects/next-collection/Untitled_Artwork (58).webp',
      'assets/projects/next-collection/Untitled_Artwork 1 (17).webp'
    ]
  },
  {
    slug:     'trimas-internship',
    index:    '04',
    category: 'Marketing',
    title:    'TriMas Internship',
    subtitle: 'Corporate Marketing Experience',
    year:     '2024',
    context:  'Professional,Marketing Internship',
    description: [
      'A real marketing internship with TriMas where I actually got stuck in. Creating assets, supporting campaign launches and contributing to the wider brand communications rather than just sitting in the background.',
      'It gave me a solid understanding of how marketing actually works in a corporate environment, the pace of it, the stakeholder side and how academic theory translates into real commercial work.'
    ],
    skills: [
      'Digital Marketing', 'Campaign Management', 'Content Creation',
      'Brand Strategy', 'Adobe Creative Suite', 'Copywriting',
      'Project Management', 'Stakeholder Communication'
    ],
    gradient: 'linear-gradient(145deg, #06060f 0%, #0e0e28 50%, #181840 100%)',
    imageCount: 36,
    imagePaths: [
      'assets/projects/trimas-internship/3group_v2.webp',
      'assets/projects/trimas-internship/Mockup 2 1.webp',
      'assets/projects/trimas-internship/Mockup 4 1.webp',
      'assets/projects/trimas-internship/Mockup 5 1.webp',
      'assets/projects/trimas-internship/Mockup 7 1.webp',
      'assets/projects/trimas-internship/Mockup 10.webp',
      'assets/projects/trimas-internship/Mockup 11 1.webp',
      'assets/projects/trimas-internship/Mockup 12 2.webp',
      'assets/projects/trimas-internship/Mockup 12 2 (1).webp',
      'assets/projects/trimas-internship/Mockup 13 1.webp',
      'assets/projects/trimas-internship/Mockup 14 1.webp',
      'assets/projects/trimas-internship/Mockup 15 1.webp',
      'assets/projects/trimas-internship/Drinktec_Social_media.webp',
      'assets/projects/trimas-internship/Drinktec_Social_media13.webp',
      'assets/projects/trimas-internship/Drinktec_Social_media14.webp',
      'assets/projects/trimas-internship/Drinktec_Social_media16.webp',
      'assets/projects/trimas-internship/beauty bottles.webp',
      'assets/projects/trimas-internship/all pull caps in water.webp',
      'assets/projects/trimas-internship/flip_caps_in_water.webp',
      'assets/projects/trimas-internship/bottle_caps.webp',
      'assets/projects/trimas-internship/bottles_with_greenry.webp',
      'assets/projects/trimas-internship/bottlers_flowers.webp',
      'assets/projects/trimas-internship/beach.webp',
      'assets/projects/trimas-internship/drink.webp',
      'assets/projects/trimas-internship/Orange_pull.webp',
      'assets/projects/trimas-internship/Isqueeze.webp',
      'assets/projects/trimas-internship/Sports_Cap_graphic.webp',
      'assets/projects/trimas-internship/final layout.webp',
      'assets/projects/trimas-internship/finalve.webp',
      'assets/projects/trimas-internship/base2.webp',
      'assets/projects/trimas-internship/asasas.webp',
      'assets/projects/trimas-internship/ChatGPT Image Jul 11, 2025, 02_52_35 PM.webp',
      'assets/projects/trimas-internship/f53eca67-ccdb-4b13-8320-6141b2f922bc.webp',
      'assets/projects/trimas-internship/Untitled-2.webp',
      'assets/projects/trimas-internship/Untitled-6.webp',
      'assets/projects/trimas-internship/Untitled-7.webp'
    ]
  },
  {
    slug:     'selfridges-project',
    index:    '05',
    category: 'Retail Design',
    title:    'Selfridges Project',
    subtitle: 'Visual Merchandising & Retail Strategy',
    year:     '2024',
    context:  'University,Visual Merchandising,67% Upper Second Class',
    description: [
      'A visual merchandising concept for Selfridges, developed as part of my uni module. I looked at how retail design, customer experience and brand storytelling come together inside one of the UK\'s most iconic stores.',
      'The brief covered window displays, in-store layouts and experiential retail, all grounded in Selfridges\' luxury positioning. It was about making something that looked great but also made commercial sense.'
    ],
    skills: [
      'Visual Merchandising', 'Retail Design', 'Space Planning',
      'Consumer Experience', 'Brand Storytelling', 'Concept Development',
      'Adobe InDesign', 'Sketch Rendering'
    ],
    gradient: 'linear-gradient(145deg, #0e0703 0%, #3a1a08 40%, #7a3510 100%)',
    imageCount: 68,
    imagePaths: [
      'assets/projects/selfridges-project/thumbnail_IMG_2787.webp',
      'assets/projects/selfridges-project/WhatsApp Image 2025-09-22 at 14.47.31_c054d6cf.webp',
      'assets/projects/selfridges-project/AI_GENERATED_,MOCKUP.webp',
      'assets/projects/selfridges-project/WhatsApp Image 2025-05-19 at 3.28.38 PM.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-0.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-1.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-2.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-3.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-4.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-5.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-6.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-7.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-8.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-9.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-10.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-11.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-12.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-13.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-14.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-15.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-16.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-17.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-18.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-19.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-20.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-21.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-22.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-23.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-24.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-25.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-26.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-27.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-28.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-29.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-30.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-31.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-32.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-33.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-34.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-35.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-36.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-37.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-38.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-39.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-40.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-41.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-42.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-43.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-44.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-45.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-46.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-47.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-48.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-49.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-50.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-51.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-52.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-53.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-54.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-55.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-56.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-57.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-58.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-59.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-60.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-61.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-62.webp',
      'assets/projects/selfridges-project/cedba3c9c99a46c8d60b7501d5d98c87Kws6J1Rq4E5VnLjA-63.webp'
    ]
  },
  {
    slug:     'cv-lab',
    index:    '06',
    category: 'Digital Product',
    title:    'CV Lab SaaS',
    subtitle: 'UI/UX Design for a CV Building Platform',
    year:     '2025',
    context:  'Personal Project,Product Design',
    description: [
      'Full UI/UX design for CV Lab, a SaaS platform for building and exporting professional CVs. Took it from initial research and wireframes all the way through to high-fidelity prototypes and a complete design system.',
      'The focus was on making it feel clean and easy to use, something that actually gives people confidence when building their CV. I put together a full component library in Figma to keep everything consistent across every screen.'
    ],
    skills: [
      'UI Design', 'UX Research', 'Figma', 'Prototyping',
      'Design Systems', 'User Flows', 'Wireframing',
      'Component Design', 'Accessibility'
    ],
    gradient: 'linear-gradient(145deg, #02050c 0%, #060f1e 50%, #0a1830 100%)',
    imageCount: 15,
    imagePaths: [
      'assets/projects/cv-lab/cv banner.webp',
      'assets/projects/cv-lab/BACKGROUND.webp',
      'assets/projects/cv-lab/check_your_cv.webp',
      'assets/projects/cv-lab/cv_analysis.webp',
      'assets/projects/cv-lab/make_cv_with_ai.webp',
      'assets/projects/cv-lab/cv_lab_intro_slide_1.webp',
      'assets/projects/cv-lab/cv_lab_intro_slide_2.webp',
      'assets/projects/cv-lab/cv_lab_intro_slide_3.webp',
      'assets/projects/cv-lab/logo.webp',
      'assets/projects/cv-lab/post1.webp',
      'assets/projects/cv-lab/photo_2025-10-26_21-10-37.webp',
      'assets/projects/cv-lab/Screenshot 2026-02-12 152701.webp',
      'assets/projects/cv-lab/Screenshot 2026-02-12 152733.webp',
      'assets/projects/cv-lab/Screenshot 2026-02-12 152759.webp',
      'assets/projects/cv-lab/Screenshot 2026-02-12 152820.webp'
    ]
  },
  {
    slug:     'graphic-design',
    index:    '07',
    category: 'Graphic Design',
    title:    'Graphic Design Showcase',
    subtitle: 'Selected Works Across Multiple Briefs',
    year:     '2023–25',
    context:  'Various,Personal & University Projects',
    description: [
      'A mix of graphic design work across personal projects, uni briefs and commercial experiments. Covers visual identities, editorial layouts, digital graphics and illustration.',
      'Each piece is a different kind of design challenge, from minimal type-led work to bold, colour-heavy brand materials. The whole body of work reflects how my design sensibility has developed through fashion, culture and digital media.'
    ],
    skills: [
      'Graphic Design', 'Typography', 'Brand Identity',
      'Editorial Design', 'Adobe Illustrator', 'Adobe Photoshop',
      'Adobe InDesign', 'Digital Illustration', 'Layout Design'
    ],
    gradient: 'linear-gradient(135deg, #0a0316 0%, #1a0840 30%, #4a0f90 60%, #8f0028 100%)',
    imageCount: 0,
    imagePaths: []
  },
  {
    slug:     'trend-forecasting',
    index:    '08',
    category: 'Trend Forecasting',
    title:    'Trend Forecasting',
    subtitle: 'Culture, Cycles & Consumer Behaviour',
    year:     '2024',
    context:  'University,Trend Forecasting Module',
    description: [
      'A uni module focused on understanding where fashion trends actually come from and how they move through the market. The research got into music, art, street culture, social movements and subcultures, and how all of that eventually shows up in what people are wearing.',
      'I mapped out the full lifecycle of a trend from the early adopters and the cultural moments that kick it off, through to mass adoption and when it gets oversaturated. Understanding that cycle is genuinely useful for buying, design and brand strategy.',
      'The module sharpened my ability to spot emerging signals before they hit the mainstream, which fed directly into the NEXT A/W 25/26 buying report I produced the same year.'
    ],
    skills: [
      'Trend Forecasting', 'Cultural Analysis', 'Consumer Research',
      'Trend Reporting', 'Moodboarding', 'Adobe InDesign',
      'Market Research', 'Fashion Theory'
    ],
    gradient: 'linear-gradient(145deg, #080c10 0%, #101c2a 35%, #0e2840 60%, #1a3a1a 100%)',
    imageCount: 37,
    imagePaths: [
      'assets/projects/trend-forecasting/Trend Forcasting-01.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-02.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-03.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-04.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-05.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-06.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-07.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-08.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-09.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-10.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-11.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-12.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-13.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-14.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-15.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-16.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-17.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-18.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-19.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-20.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-21.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-22.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-23.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-24.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-25.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-26.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-27.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-28.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-29.webp',
      'assets/projects/trend-forecasting/Trend Forcasting-30.webp',
      'assets/projects/trend-forecasting/Trend Zeitgeist Pack with Garement-1.webp',
      'assets/projects/trend-forecasting/Trend Zeitgeist Pack with Garement-2.webp',
      'assets/projects/trend-forecasting/Trend Zeitgeist Pack with Garement-3.webp',
      'assets/projects/trend-forecasting/Trend Zeitgeist Pack with Garement-4.webp',
      'assets/projects/trend-forecasting/Trend Zeitgeist Pack with Garement-5.webp',
      'assets/projects/trend-forecasting/Trend Zeitgeist Pack with Garement-6.webp',
      'assets/projects/trend-forecasting/Trend Zeitgeist Pack with Garement-7.webp'
    ]
  },
  {
    slug:     'slimmer-app',
    index:    '09',
    category: 'App Design',
    title:    'Slimmer App',
    subtitle: 'AI-Powered Women\'s Fitness',
    year:     '2025',
    context:  'Personal Project,UI/UX & Product Design',
    description: [
      'Slimmer is a women\'s fitness app built around the idea that no two bodies are the same. It uses AI facial scanning to identify personal focus areas and builds a workout plan around those specific zones, taking the guesswork out of training.',
      'On the nutrition side, you just take a photo of your food and the AI logs the calories and macros automatically. Water tracking is built in alongside, so users get the full picture without having to manually enter anything.',
      'The whole thing was designed to feel clean and premium, aimed at women who want results without the faff. Every screen from the onboarding scan through to the daily dashboard was built to feel intuitive and motivating.'
    ],
    skills: [
      'UI/UX Design', 'Mobile App Design', 'Figma',
      'Prototyping', 'User Research', 'AI Integration',
      'Product Design', 'Visual Design', 'Branding'
    ],
    gradient: 'linear-gradient(145deg, #0f0018 0%, #240030 35%, #3d0050 60%, #5a0060 80%, #2a0030 100%)',
    imageCount: 61,
    imagePaths: [
      'assets/projects/slimmer-app/photo_2026-04-16_22-19-47.webp',
      'assets/projects/slimmer-app/launch screen.webp',
      'assets/projects/slimmer-app/Get Started.webp',
      'assets/projects/slimmer-app/greeting page.webp',
      'assets/projects/slimmer-app/enter name.webp',
      'assets/projects/slimmer-app/enter age.webp',
      'assets/projects/slimmer-app/enter height.webp',
      'assets/projects/slimmer-app/Whats your weight.webp',
      'assets/projects/slimmer-app/how would you describe your face & body.webp',
      'assets/projects/slimmer-app/what do you want to work on.webp',
      'assets/projects/slimmer-app/what are your weight related goals.webp',
      'assets/projects/slimmer-app/How Much time do you have today.webp',
      'assets/projects/slimmer-app/when did you last feel happy.webp',
      'assets/projects/slimmer-app/what do you want to acheive.webp',
      'assets/projects/slimmer-app/building plan.webp',
      'assets/projects/slimmer-app/results page.webp',
      'assets/projects/slimmer-app/home page.webp',
      'assets/projects/slimmer-app/calorie tracker screen.webp',
      'assets/projects/slimmer-app/paywall 1.webp',
      'assets/projects/slimmer-app/Testimonails sceen.webp',
      'assets/projects/slimmer-app/Notifcations.webp',
      'assets/projects/slimmer-app/camera permissions.webp',
      'assets/projects/slimmer-app/privacy screen.webp',
      'assets/projects/slimmer-app/SLIMMER_APP_LOGO.webp',
      'assets/projects/slimmer-app/backup.webp',
      'assets/projects/slimmer-app/CALORIES-A.webp',
      'assets/projects/slimmer-app/CALORIES-B.webp',
      'assets/projects/slimmer-app/PERSONALIZED-A.webp',
      'assets/projects/slimmer-app/PERSONALIZED-B.webp',
      'assets/projects/slimmer-app/SMARTINSIGHT-A.webp',
      'assets/projects/slimmer-app/SMARTINSIGHT-B.webp',
      'assets/projects/slimmer-app/21days.webp',
      'assets/projects/slimmer-app/slide_2.webp',
      'assets/projects/slimmer-app/slide_3.webp',
      'assets/projects/slimmer-app/slimmer_add1.webp',
      'assets/projects/slimmer-app/menopause_ad.webp',
      'assets/projects/slimmer-app/lymphatic.webp',
      'assets/projects/slimmer-app/look younger.webp',
      'assets/projects/slimmer-app/Acheive your Dream Body.webp',
      'assets/projects/slimmer-app/are you ready for change.webp',
      'assets/projects/slimmer-app/by taking action today.webp',
      'assets/projects/slimmer-app/Did you know.webp',
      'assets/projects/slimmer-app/Harvard quote.webp',
      'assets/projects/slimmer-app/in just 2 weeks#.webp',
      'assets/projects/slimmer-app/the face & body you miss.webp',
      'assets/projects/slimmer-app/what you could start to see.webp',
      'assets/projects/slimmer-app/your all set.webp',
      'assets/projects/slimmer-app/1.webp',
      'assets/projects/slimmer-app/2.webp',
      'assets/projects/slimmer-app/3.webp',
      'assets/projects/slimmer-app/4.webp',
      'assets/projects/slimmer-app/5.webp',
      'assets/projects/slimmer-app/6.webp',
      'assets/projects/slimmer-app/7.webp',
      'assets/projects/slimmer-app/8.webp',
      'assets/projects/slimmer-app/9.webp',
      'assets/projects/slimmer-app/10.webp',
      'assets/projects/slimmer-app/11.webp',
      'assets/projects/slimmer-app/12.webp',
      'assets/projects/slimmer-app/13.webp'
    ]
  },
  {
    slug:     'make-progress',
    index:    '10',
    category: 'Brand Identity',
    title:    'Make Progress',
    subtitle: 'Event Branding & Paid Social',
    year:     '2023',
    context:  'Freelance,Brand Identity & Meta Advertising',
    description: [
      'Make Progress was a community event in Birmingham city centre that brought together local businesses from learning, skills, sport and community sectors and put them in front of the public. Simple idea: give people access to opportunities they might not otherwise find, all under one roof.',
      'My job was to build the brand identity from scratch and run Meta ad campaigns targeting local businesses, getting them to buy a stall at the event. I had to create a visual identity that felt energetic and inclusive, and the ads needed to convert people who had never heard of it.',
      'Looking back, this was one of my earliest proper design projects and it taught me a lot, both about working with a client and about how brand and marketing actually connect. The visual identity is something I would approach very differently now, but running live paid campaigns and delivering to a real brief at that stage was genuinely valuable.'
    ],
    skills: [
      'Brand Identity', 'Logo Design', 'Meta Ads',
      'Paid Social', 'Copywriting', 'Adobe Illustrator',
      'Adobe Photoshop', 'Event Design', 'Marketing Strategy'
    ],
    gradient: 'linear-gradient(145deg, #0a0e06 0%, #141e08 35%, #1e300a 60%, #2a420e 100%)',
    imageCount: 0,
    imagePaths: []
  }
];
